##
#
# 感谢p3terx大神的一键编译脚本
# 
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
#修改以下代码或者开启触发开关都好，要严格按格式对好,前面有多少空格也要看清楚
#代码里有 name: 后面的内容随便改,冒号后面是有个空格的,如果修改固件名字就要考虑能不能显示出你想要的


name: r30b1 luci闭源固件

on: 

  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: 编译OpenWrt-immortalwrt-mt798x固件
    runs-on: ubuntu-22.04

    steps:
    - name: 准备结束
      uses: actions/checkout@v3

    - name: 开始安装编译所需系统
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo $(nproc)
        free -h
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install sudo time git-core subversion build-essential gcc-multilib libncurses5-dev zlib1g-dev gawk flex gettext wget unzip grep rsync python3 tree python3-distutils
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 下载固件源码
      run: |
        pwd
        git clone -b clt-r30b1 --single-branch --depth=1 https://github.com/benboguan/immortalwrtARM openwrt
        # ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        ls -l

    # 插件包,不要可用注释
    # - name: feeds add fw876/helloworld
    #   run: |
    #     cd openwrt
    #     sed -i "/helloworld/d" "feeds.conf.default"
    #     echo "src-git helloworld https://github.com/fw876/helloworld.git" >> "feeds.conf.default"

    - name: 部署feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 加载.config设置
      run: |
        cp config/r30b1-luci.config openwrt/.config
        cd openwrt
        rm -rf ./bin ./build_dir ./tmp
        make defconfig
        cat ./.config

    - name: 备份.config文件
      run: |
        mkdir ./bin
        cp config/r30b1-luci.config ./bin/config.bak

    - name: 更改固件IP 192.168.110.1
      run: |
        cd openwrt
        sed -i "s/192.168.1.1/192.168.110.1/" package/base-files/files/bin/config_generate
        cat package/base-files/files/bin/config_generate|grep lan\)

    - name: 编译固件
      run: |
        cd openwrt
        find ./ -name *gcc
        make download -j8
        rm -rf build.log
        # | grep -i error
        make -j$(expr $(nproc) + 12) V=99 2>&1 | tee build.log | grep -i error
        cp build.log ./bin
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: 整理固件文件
      id: organize
      run: |
        cd openwrt/bin/
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: 保存工作文件
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: 设置Release路径
      run: |
        touch release.txt
        cd openwrt/bin/targets/*/*
        echo "RELEASE_PATH=$PWD" >> $GITHUB_ENV

    - name: 打包bin目录
      run: |
        cd openwrt
        tar -zcvf bin_dir.tar.gz ./bin/
        mv bin_dir.tar.gz ${{ env.RELEASE_PATH }}/
        rm -rf ${{ env.RELEASE_PATH }}/packages

    - name: 打包dl目录
      run: |
        cd openwrt
        tar -zcvf dl.tar.gz ./dl/
        mv dl.tar.gz ${{ env.RELEASE_PATH }}/

    - name: 上传固件到release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        body_path: release.txt
        files: ${{ env.RELEASE_PATH }}/*
